import { redirect } from "next/navigation";
import { createClient, createAdminClient } from "@/lib/supabase/server";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { AdminGovernanceDashboard } from "@/components/admin/AdminGovernanceDashboard";
import { calculateVendorHealthScore } from "@/lib/vendor/health";
import { detectComputedWarnings } from "@/lib/vendor/warnings";
import type { Profile } from "@/types";

export const dynamic = "force-dynamic";

const ADMIN_EMAILS = (process.env.ADMIN_EMAILS ?? "").split(",").map((e) => e.trim());

export default async function AdminGovernancePage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  if (!ADMIN_EMAILS.includes(user.email ?? "")) redirect("/dashboard");

  const db = await createAdminClient();
  const { data: profile } = await db.from("profiles").select("*").eq("id", user.id).single();

  // Fetch approved vendors for at-risk analysis
  const { data: vendors } = await db
    .from("vendors")
    .select("id, business_name, city, category, status, rating, review_count, response_rate, cancellation_rate, completed_jobs_count, suspicious_flag, suspicious_reason, last_active_at, verification_level, bio, phone, min_price, instagram_url, website_url, subscription_plan, created_at, updated_at, profile:profiles(full_name, email)")
    .eq("status", "approved")
    .order("created_at", { ascending: false })
    .limit(500);

  // Compute health + warnings for each vendor, filter to at-risk
  const allVendors = (vendors ?? []).map((v) => {
    const health   = calculateVendorHealthScore(v);
    const warnings = detectComputedWarnings(v);
    return { ...v, health, warnings };
  });

  const atRiskVendors = allVendors.filter((v) => v.health.isAtRisk || v.suspicious_flag);

  // Health distribution
  const distribution = { excellent: 0, good: 0, fair: 0, poor: 0, critical: 0 };
  for (const v of allVendors) distribution[v.health.tier]++;

  // Fetch stored unresolved warnings
  const { data: storedWarnings } = await db
    .from("vendor_warnings")
    .select(`
      id, type, severity, title, message, admin_notes, auto_generated,
      resolved, resolved_at, created_at,
      vendor:vendors(id, business_name, status)
    `)
    .eq("resolved", false)
    .order("created_at", { ascending: false })
    .limit(100);

  const activeWarnings = (storedWarnings ?? []).map((w) => ({
    id: w.id,
    type: w.type,
    severity: w.severity,
    title: w.title,
    message: w.message,
    adminNotes: w.admin_notes,
    autoGenerated: w.auto_generated,
    resolved: w.resolved,
    resolvedAt: w.resolved_at,
    createdAt: w.created_at,
    vendor: w.vendor as unknown as { id: string; business_name: string; status: string } | null,
  }));

  return (
    <DashboardLayout user={profile as Profile}>
      <AdminGovernanceDashboard
        atRiskVendors={atRiskVendors.map((v) => ({
          id: v.id,
          business_name: v.business_name,
          city: v.city,
          category: v.category,
          status: v.status,
          suspicious_flag: v.suspicious_flag,
          suspicious_reason: v.suspicious_reason ?? null,
          health: v.health,
          warnings: v.warnings,
          profile: v.profile as unknown as { full_name: string; email: string } | null,
        }))}
        activeWarnings={activeWarnings}
        healthDistribution={distribution}
        totalApproved={allVendors.length}
      />
    </DashboardLayout>
  );
}
